# site settings
title: Tủ bếp SB
subtitle: by Smartview
email: dangthanhhai@gmail.com
description: Các loại tủ bếp vật liệu thân thiện môi trường.
baseurl: # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: Văn phòng B19 Tầng 16 tòa nhà TNR, số 54 Nguyễn Chí Thanh, Q.Đống Đa, Hà Nội.<br>Xưởng sản xuất 1 Cụm 8, xã Long Xuyên, huyện Phúc Thọ, TP Hà Nội.
city: Hanoi
state: 
zip_code: 10000
country: VietNam
phone: 0338500022; 0982835886;
hotline: 0338500022

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 7

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url: https://gitlab.com/
googleplus_url: https://plus.google.com/
instagram_url: https://instagram.com
linkedin_url: https://www.linkedin.com/
pinterest_url:
slack_url:
twitter_url: https://twitter.com/

# build settings
markdown: kramdown

sass:
  style: compressed
  
defaults:
  - scope:
      path: "assets/images/auto-image"
    values:
      image: true

# plugins
plugins:
  - jekyll-seo-tag 
  